# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: contact@anenta.com
title: Anenta Waste
description: Simple Waste Management Solutions

baseurl: "/anenta-waste" # the subpath of your site, e.g. /blog
url: "https://kujilabs.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
# theme: minima
sass:
  style: compressed

gems: 
  - jekyll-assets
  - jekyll-seo-tag

autowrite: true

assets:
  sources:
    - _assets/
    - _assets/css/
    - _assets/css/plugins/
    - _assets/images/
    - _assets/images/backgrounds/
    - _assets/images/icons/sided-services/
    - _assets/images/icons/
    - _assets/images/layout/
    - _assets/images/vector/
    - _assets/js/
    - _assets/fonts/
  digest: false        
  compress:
    css: true  
    js: true

anenta: 
  company_name: Anenta Ltd
  web_address: https://www.anentawaste.com
  int_telephone: +44 330 122 2143
  telephone: 033 0122 2143
  address: ["The Light Bulb", "1 Filament Walk", "London", "SW18 4GQ"]
